server:
  port: 8091
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testTaskDB
    driverClassName: org.postgresql.Driver
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true

auth:
  access-secret-key: this.secret.key.should.be.replaced
  refresh-secret-key: this.secret.key.should.be.replaced.as.well
  access-token-expiration-time-ms: 3600000
  refresh-token-expiration-time-ms: 3600000